#!/bin/bash

LOCATIONS=(zsh git tmux)

for LOCATION in ${LOCATIONS[@]}; do 
  TARGET=$HOME

  # Getting the install location if specified
  if [ -e $LOCATION/base.location ]; then
    # loading location
    TARGET=$(readlink -f "$(eval echo $(< "$LOCATION/base.location"))")
  fi

  stow -t $TARGET --dotfiles --ignore="base.location" $LOCATION -n -vv
done
