#!/bin/bash

LOCATIONS=(zsh git tmux nvim alacritty fastfetch)

for LOCATION in ${LOCATIONS[@]}; do 
  echo "Deploying $LOCATION config."
  TARGET=$HOME

  # Getting the install location if specified
  if [ -e $LOCATION/base.location ]; then
    # loading location and create directory
    TARGET=$(readlink -f "$(eval echo $(< "$LOCATION/base.location"))")
    mkdir -p $TARGET
  fi

  stow -t $TARGET --dotfiles --ignore="base.location" $LOCATION
done
